{{/* Current apiVersion of ingress */}}
{{- $apiVersion := "extensions/v1beta1" }}
{{- $gitVersion := $.Capabilities.KubeVersion.GitVersion -}}
{{- $apiVersions := $.Capabilities.APIVersions -}}
{{- if and ($apiVersions.Has "networking.k8s.io/v1") (semverCompare ">= 1.19" $gitVersion) -}}
{{- $apiVersion := "networking.k8s.io/v1" -}}
{{- else if and ($apiVersions.Has "networking.k8s.io/v1beta1") (semverCompare ">=1.14-0" $gitVersion) -}}
{{- $apiVersion := "networking.k8s.io/v1beta1" -}}
{{- end -}}

{{/* Resource definition */}}
{{- with .Values.resources.ingress }}
{{- if .enabled }}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ template "imgproxy.fullname" $ }}
  labels:
    app: {{ template "imgproxy.fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .tls }}
  tls:
    {{- range .tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          {{- $name := include "imgproxy.fullname" $ }}
          {{- $path := default "/" $.Values.features.server.pathPrefix }}
          {{- if eq $apiVersion "networking.k8s.io/v1" }}
          - path: {{ $path | quote }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $name | quote }}
                port:
                  number: 80
          {{- else }}
          - path: {{ $path | quote }}
            backend:
              serviceName: {{ $name | quote }}
              servicePort: 80
          {{- end }}
{{- end }}
{{- end }}
{{- end }}
